remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
title: Cross Benefits Documentation
description: Comprehensive documentation for VA benefits systems
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore 
